services:
    bushido_ioqr_code.service:
        class: BushidoIO\QRCodeBundle\Service\QRcodeService
        calls:
            - [ setContainer, [ @service_container ] ]

    bushido_ioqr_code.twig.qr_code_url_extension:
        class: BushidoIO\QRCodeBundle\Twig\QRCodeUrlExtension
        tags:
            - { name: twig.extension }
        calls:
            - [ setContainer, [ @service_container ] ]
